/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.form;

import controller.Controller;
import domain.Selection;
import exceptions.ServerException;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import ui.listeners.ListenerDeleteMatch;
import ui.table.ModelTableSelection;

/**
 *
 * @author Veljko
 */
public class FrmViewSelection extends javax.swing.JFrame {

    /**
     * Creates new form FrmViewSelection
     */
    int startPositon = 0;
    int tableSize = 5;
    static Selection selection;
    ResourceBundle resourceBundle;

    public FrmViewSelection(Selection selection) {
        this.selection = selection;
        initComponents();
        try {
            selection.setMatches(Controller.getInstance().getMatches(selection));
        } catch (Exception ex) {
            Logger.getLogger(FrmViewSelection.class.getName()).log(Level.SEVERE, null, ex);
        }
        initListeners();
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JlblSelection = new javax.swing.JLabel();
        jlblSelectionName = new javax.swing.JLabel();
        JLblBackward = new javax.swing.JLabel();
        JLblForward = new javax.swing.JLabel();
        jlbRang = new javax.swing.JLabel();
        jblPoints = new javax.swing.JLabel();
        jlblRang = new javax.swing.JLabel();
        jlblPoints = new javax.swing.JLabel();
        jlblNumberMatches = new javax.swing.JLabel();
        comboTableSize = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMatches = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JlblSelection.setText("Selection:");

        jlblSelectionName.setText("jLabel1");

        JLblBackward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Fast-backward-icon.png"))); // NOI18N
        JLblBackward.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLblBackwardMouseClicked(evt);
            }
        });

        JLblForward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Button-Forward-icon.png"))); // NOI18N
        JLblForward.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLblForwardMouseClicked(evt);
            }
        });

        jlbRang.setText("Rang:");

        jblPoints.setText("Points");

        jlblRang.setText("jLabel3");

        jlblPoints.setText("jLabel4");

        jlblNumberMatches.setText("Prikaz broja meceva:");

        comboTableSize.setModel(new javax.swing.DefaultComboBoxModel<>());
        comboTableSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTableSizeActionPerformed(evt);
            }
        });

        jTableMatches.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(jTableMatches);

        btnDelete.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblNumberMatches)
                .addGap(58, 58, 58)
                .addComponent(comboTableSize, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlbRang, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(jblPoints, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(378, 378, 378)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblRang)
                            .addComponent(jlblPoints))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JlblSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(339, 339, 339)
                        .addComponent(jlblSelectionName, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLblBackward)
                        .addGap(125, 125, 125)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JLblForward)
                        .addGap(56, 56, 56))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlblSelection)
                    .addComponent(jlblSelectionName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblRang)
                    .addComponent(jlbRang))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblPoints)
                    .addComponent(jlblPoints))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblNumberMatches)
                            .addComponent(comboTableSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLblForward, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JLblBackward, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete)
                        .addGap(24, 24, 24))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JLblBackwardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLblBackwardMouseClicked
        if (startPositon - tableSize < 0) {
            return;
        }
        startPositon -= tableSize;
        setTable();
    }//GEN-LAST:event_JLblBackwardMouseClicked

    private void JLblForwardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLblForwardMouseClicked
        try {
            if (startPositon + tableSize >= Controller.getInstance().getMatches(selection).size()) {
                return;
            }
        } catch (Exception ex) {
            Logger.getLogger(FrmViewSelection.class.getName()).log(Level.SEVERE, null, ex);
        }
        startPositon += tableSize;
        setTable();
    }//GEN-LAST:event_JLblForwardMouseClicked

    private void comboTableSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTableSizeActionPerformed
        tableSize = (int) comboTableSize.getSelectedItem();
        startPositon = 0;
        setTable();
    }//GEN-LAST:event_comboTableSizeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmViewSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmViewSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmViewSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmViewSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmViewSelection(selection).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLblBackward;
    private javax.swing.JLabel JLblForward;
    private javax.swing.JLabel JlblSelection;
    private javax.swing.JButton btnDelete;
    private javax.swing.JComboBox<Integer> comboTableSize;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMatches;
    private javax.swing.JLabel jblPoints;
    private javax.swing.JLabel jlbRang;
    private javax.swing.JLabel jlblNumberMatches;
    private javax.swing.JLabel jlblPoints;
    private javax.swing.JLabel jlblRang;
    private javax.swing.JLabel jlblSelectionName;
    // End of variables declaration//GEN-END:variables

    public void setTable() {
        try {
            selection.setMatches(Controller.getInstance().getMatches(selection));
            ModelTableSelection modelTableSelection = new ModelTableSelection(selection.getMatches(), startPositon, tableSize);
            jTableMatches.setModel(modelTableSelection);
            validate();
        } catch (Exception ex) {
            Logger.getLogger(FrmViewSelection.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void prepareView() {
        Locale locale = Controller.getLocale();
        resourceBundle = ResourceBundle.getBundle("resourceBundles.ResourceBundle_FrmViewSelection_" + locale);
        JlblSelection.setText(resourceBundle.getString("Selection"));
        jblPoints.setText(resourceBundle.getString("Points"));
        jlbRang.setText(resourceBundle.getString("Rank"));
        jlblNumberMatches.setText(resourceBundle.getString("jlblNumberMatches"));
        try {
            btnDelete.setEnabled(Controller.getInstance().readAdministrator());
        } catch (Exception ex) {
            Logger.getLogger(FrmViewSelection.class.getName()).log(Level.SEVERE, null, ex);
        }
        btnDelete.setText(resourceBundle.getString("btnDelete"));
      

        jlblSelectionName.setText(selection.getName());
        jlblPoints.setText(selection.getPoints() + "");
        jlblRang.setText(selection.getRang() + "");

        comboTableSize.addItem(5);
        comboTableSize.addItem(10);
        comboTableSize.addItem(15);
    }

    private void initListeners() {
        btnDelete.addActionListener(new ListenerDeleteMatch(this));
        jTableMatches.addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                jTableMatches.getColumnModel().getColumn(1).setMaxWidth(60);
                jTableMatches.getColumnModel().getColumn(4).setMinWidth(150);
            }
        });
    }

    public ResourceBundle getResourceBundle() {
        return resourceBundle;
    }

    public JTable getjTableMatches() {
        return jTableMatches;
    }

    public void setjTableMatches(JTable jTableMatches) {
        this.jTableMatches = jTableMatches;
    }

    public Selection getSelection() {
        return selection;
    }

    public int getStartPositon() {
        return startPositon;
    }   
    
    
}
