/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.form;

import controller.Controller;
import domain.Selection;
import exceptions.ServerException;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import ui.listeners.ListenerDeleteSelection;
import ui.table.ModelTableRangList;

/**
 *
 * @author Veljko
 */
public class FrmViewRangList extends javax.swing.JFrame {

    /**
     * Creates new form FrmViewRangList
     */
    int tableSize = 5;
    int startPosition = 0;
    List<Selection> selections;
    ResourceBundle resourceBundle;

    public FrmViewRangList() {
        initComponents();
        prepareView();
        setTable();
        initListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRangList = new javax.swing.JTable();
        JLblBackward = new javax.swing.JLabel();
        JLblForward = new javax.swing.JLabel();
        JLblTableSize = new javax.swing.JLabel();
        comboTableSize = new javax.swing.JComboBox<>();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableRangList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableRangList);

        JLblBackward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Fast-backward-icon.png"))); // NOI18N
        JLblBackward.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLblBackwardMouseClicked(evt);
            }
        });

        JLblForward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Button-Forward-icon.png"))); // NOI18N
        JLblForward.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLblForwardMouseClicked(evt);
            }
        });

        JLblTableSize.setText("Prikaz broja reprezentacija:");

        comboTableSize.setModel(new javax.swing.DefaultComboBoxModel<>());
        comboTableSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTableSizeActionPerformed(evt);
            }
        });

        btnDelete.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(JLblBackward)
                .addGap(72, 72, 72)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JLblForward)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLblTableSize)
                        .addGap(114, 114, 114)
                        .addComponent(comboTableSize, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLblTableSize)
                    .addComponent(comboTableSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLblForward)
                            .addComponent(JLblBackward)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnDelete)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JLblBackwardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLblBackwardMouseClicked
        if (startPosition - tableSize < 0) {
            return;
        }
        startPosition -= tableSize;
        setTable();
    }//GEN-LAST:event_JLblBackwardMouseClicked

    private void JLblForwardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLblForwardMouseClicked
        if (startPosition + tableSize >= selections.size()) {
            return;
        }
        startPosition += tableSize;
        setTable();
    }//GEN-LAST:event_JLblForwardMouseClicked

    private void comboTableSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTableSizeActionPerformed
        tableSize = (int) comboTableSize.getSelectedItem();
        startPosition = 0;
        setTable();
    }//GEN-LAST:event_comboTableSizeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmViewRangList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmViewRangList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmViewRangList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmViewRangList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmViewRangList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLblBackward;
    private javax.swing.JLabel JLblForward;
    private javax.swing.JLabel JLblTableSize;
    private javax.swing.JButton btnDelete;
    private javax.swing.JComboBox<Integer> comboTableSize;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRangList;
    // End of variables declaration//GEN-END:variables

    public void setTable() {
        ModelTableRangList modelTable = null;
        try {
            selections = controller.Controller.getInstance().getRangList();
            modelTable = new ModelTableRangList(selections, startPosition, tableSize);
        } catch (ServerException ex) {
            Logger.getLogger(FrmViewRangList.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTableRangList.setModel(modelTable);
    }

    private void prepareView() {
        Locale locale = Controller.getLocale();
        resourceBundle = ResourceBundle.getBundle("resourceBundles.ResourceBundle_FrmViewRangList_" + locale);
        JLblTableSize.setText(resourceBundle.getString("numberSelection"));
        btnDelete.setText(resourceBundle.getString("btnDelete"));

        comboTableSize.removeAllItems();
        comboTableSize.addItem(5);
        comboTableSize.addItem(10);
        comboTableSize.addItem(15);

        try {
            btnDelete.setEnabled(Controller.getInstance().readAdministrator());
        } catch (ServerException ex) {
            Logger.getLogger(FrmViewRangList.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void initListeners() {
        btnDelete.addActionListener(new ListenerDeleteSelection(this));

    }

    public JTable getjTableRangList() {
        return jTableRangList;
    }

    public ResourceBundle getResourceBundle() {
        return resourceBundle;
    }
    
    public int getStartPositon() {
        return startPosition;
    }  

    public List<Selection> getSelections() {
        return selections;
    }

    public void setSelections(List<Selection> selections) {
        this.selections = selections;
    }
    
    
}
